### ISSUE TITLE
Beta Release Tracking

### ISSUE THREAD

**Issue by JeremyJonas** [aws-samples/aws-iot-kickstart#13]
Beta release is major refactor of the Sputnik example code to make the project modular, API driven, increase code coverage, and generally make it easy to consume and integrate into actual solutions.

> `Attention:` All versions of Sputnik are to be considered "example" code and are provided "AS IS" under the [Amazon Software License](https://aws.amazon.com/asl/).

The **Beta Release** is being tracking by the [Sputnik Beta Release Project](https://github.com/aws-samples/aws-iot-kickstart/projects/1) and will mark the first official release of the project.

## Key Features/Requirements:

- [x] Refactor project to be modular
  - Enable using specific parts of the project rather than "all or nothing"
- [ ] Refactor API (Schema First) (**WIP**)
  - [x] Separate API schema and operations
  - [ ] Refactor API schema (**WIP**) #19 
    - [ ] Consistent naming of types, querier, mutation, etc (**WIP**)
    - [ ] Consistent operation inputs and pagination (**WIP**)
    - [ ] Consistent mutation responses (**WIP**)
  - [ ] Refactor and optimize API operations #20
  - [x] Use [graphql codegen](https://graphql-code-generator.com/) to auto generate everything
    - [x] Generate [Types](https://graphql-code-generator.com/docs/plugins/typescript)
    - [x] Generate [Angular services](https://graphql-code-generator.com/docs/plugins/typescript-apollo-angular)
    - [x] Generate [graphql-request](https://graphql-code-generator.com/docs/plugins/typescript-graphql-request)
- [ ] Refactor [all CloudFormation templates](https://github.com/aws-samples/aws-iot-kickstart/tree/prerelease/beta/packages/infra/sputnik-infra/src/stack/nested/existing/SputnikStack/cf) into CDK (**WIP**) #21
- [ ] Refactor / Fix angular web project (**WIP**)
   - [ ] Refactor all services to use new API and generated services (**WIP**) #22
  - [ ] Refactor all models to use generated types (**WIP**) #23
  - [ ] Make sure all subscriptions are wired up and working #24
  - [x] Refactor and upgrade the amplify authentication flow and integration
  - [ ] ...
- [ ] Improve code coverage for all critical paths #25
  - [ ] Infra (**WIP**)
  - [ ] Web
  - [ ] Api
  - [ ] Lambdas (**WIP**)
  - [ ] ...
- [x] Enable CI/CD deployments and publishing
- [ ] Improve development and tooling
  - [x] Consistent ESLint configuration project wide (**WIP**)
  - [ ] Efficient builds and tests
  - [ ] ...
- [ ] Update documentation #26
  - [ ] General project documentation
  - [ ] Developer documentation
  - [ ] Quick start documentation
  - [x] "Path to Production" documentation
  - [ ] ...
- [ ] ...

Once all the above have been completed, depending on the level of code coverage and the stability of the project overall, the core contributor team will decide on either release `v0` or `v1`. Anything prior to `v1` will not follow Semver and may have breaking changes between minor/patch releases. However from `v1` onward, the project will follow strict Semver releases and be considered "stable". Obviously, without comprehensive test coverage this is not possible to maintain, as such will stay in <= v0 until team is confident in ongoing maintainability.
